fribidi/fribidi

lib/fribidi-bidi.c, lib/fribidi-bidi.h, lib/fribidi-common.h, lib/run.h
This function reorders all runs from logical to final visual order, similar to
fribidi_reorder_line() but without reordring the text inside the runs, so that
it can be used e.g. with HarfBuzz.
=> Add fribidi_reorder_runs()

Makefile.am
Calling bootstrap from make causes configure to be called again with no arguments.
fribidi/fribidi#35
=> Do not call bootstrap from make

doc/Makefile.am, lib/fribidi-common.h, lib/fribidi.def
Parallel build was failing while building the man pages. `doc/Makefile.am` tries cleverly to handle the fact that c2man produces all the man pages at once, following the approach described in:
https://www.gnu.org/software/automake/manual/html_node/Multiple-Outputs.html
However this is failing because c2man is not generating all the requested man pages, so the rule ends being run multiple times instead of once and parallel builds are broken. One of the requested pages is
for a function that doesn’t exist, `fribidi_log2vis_get_embedding_levels_ex`, so I removed it from `fribidi.def`.
Two functions were not documented, so I added minimal documentation for them.
But the last two are for variables not functions and c2man does not like that it seems so I added a hack to drop these two as well …
=> Fix parallel build

configure.ac
This is more consistent and matches pretty much every other autotools setup.
=> Keep micro version in full version even if 0

doc/Makefile.am
POSIX says the number after `head -n` should be a positive interger.
```
head: illegal line count -- -2
head: illegal line count -- -2
head: illegal line count -- -2
head: illegal line count -- -2
```
=> Fix documentation installation on FreeBSD

doc/meson.build
Follow-up fix to commit c8ad556. The .def file contains all
exported symbols including exported variables. The autotools
docs build only installs man pages for the functions however,
so we need to special-case the two variable names if we don't
want to pass '-v' to c2man to create man pages for the exported
symbols as well.
=> meson: fix docs install

doc/meson.build
Fixes #79
Only very lightly tested.
=> meson: don't require c2man for tarball with pre-generated man pages

gen.tab/meson.build
They are run during the build and not installed in the end. Without
this one gets the following error from meson: "ERROR: Can not use
target gen-unicode-version as a generator because it is cross-built
and no exe wrapper is defined. You might want to set it to native
instead."
Closes #87.
=> Build generator executables natively

test/unicode-conformance/BidiCharacterTest.c, test/unicode-conformance/BidiTest.c
Hi,
This MR updates the test programs so that they build on pre-C99 compilers as well, since the fribidi library itself builds on such compilers already.
With blessings, thank you!
=> tests: Fix build on pre-C99 compilers

test/unicode-conformance/meson.build
It appears I missed an executable in my previous commit since it wasn't getting run by default on the VS backend, apologies. This should be everything, since the executables in gen.tab don't appear to link libfribidi. The ninja backend with msvc runs successfully with this commit.
=> meson: Pass visibility args to test executable

NEWS, lib/fribidi-bidi.c, lib/fribidi-char-sets.h, lib/fribidi-common.h
Found via `codespell -q 3 -S ./gen.tab`
=> Misc. source comment and documentation typo fixes

.travis.yml
* Removed 'sudo'. See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
* Reverted the static meson version, since 0.48.1 has been released.
=> Updated Travis settings

lib/fribidi.h
Resolves https://github.com/fribidi/fribidi/issues/109
I can't actually test on this machine to verify it solves the issue, so if someone else quickly could that would be fantastic (@moham96?).
To ensure issues like this don't crop up in the future it would probably be best to pass `-fvisibility=hidden` to autotools builds as well, but I think that's best addressed by someone more familiar with it than I.
=> Properly export fribidi_unicode_version

lib/fribidi-arabic.c
Found this while porting fribidi to wasm [here](https://github.com/harfbuzz/harfbuzzjs/commit/c9e3680032d8bd1f5d4aca62a86fc3156824266b), it is he only thing fribidi uses from libc but harfbuzz isn't and people advice us to not use libc's bsearch for performance reasons https://github.com/harfbuzz/harfbuzz/issues/1602 so lets do the same here also
=> Avoid use of libc's bsearch for performance and portability reasons

meson.build, meson_options.txt
This allows to optionally not build tests, nor binaries.
=> meson: allow to disable building tests and binaries

meson.build
`get_option('buildtype')` returns `'custom'` in most of the cases
where `-Ddebug` is set. However, `get_option('debug')` will always be
set correctly if the user sets `-Dbuildtype`. See the following table
for the mapping:
https://mesonbuild.com/Builtin-options.html#build-type-options
=> meson: Use the `debug` option directly instead of `buildtype`

bin/fribidi-main.c
Fixes #94.
No idea if this option ever existed.  Both the help text mentions and the lack of implementation go back to "Initial revision" 63d12e574eb5cfe95290b303bac0950c25afe397 from 2004...
=> Drop non-existent --changes from help text

bin/Makefile.am, bin/meson.build, configure.ac, fribidi.pc.in, lib/Makefile.am, lib/fribidi-bidi-types.h, lib/fribidi-bidi.h, lib/fribidi-common.h, lib/fribidi-deprecated.h, lib/fribidi-joining-types.h, lib/fribidi-unicode.h, lib/fribidi.h, lib/meson.build, meson.build, test/unicode-conformance/Makefile.am, test/unicode-conformance/meson.build
* when the shared library is compiled, it is set to dllexport
* when the shared library is used, it is set to dllimport
* when the static library is used, it is set to nothing
(FRIBIDI_LIB_STATIC must be passed to the preprocessor)
* Cflags.private is set to -DFRIBIDI_LIB_STATIC in fribidi.pc (used
with pkgconf)
=> Fix FRIBIDI_ENTRY on Windows

lib/fribidi-bidi.c
Copy the logic from `fribidi_get_par_embedding_levels_ex`.
Most likely, this should have been added in commit f20b6480b9cd46dae8d82a6f95d9c53558fcfd20, which added support for Unicode 6.3 in general and isolates in particular, but was omitted by accident.
=> Skip isolates in fribidi_get_par_direction

meson.build
meson seemingly doesn't have a section for cflags.private, so the flags will have to go to the regular cflags for now
it can be replaced by manual sed or similar to append that line if wanted
Fixes m-ab-s/media-autobuild_suite#1735
Fixes https://github.com/fribidi/fribidi/issues/156
=> meson: add fribidi_static_cargs to extra_cflags

lib/fribidi-common.h
fix issue #150: compile time warnings
There is one scenario:
FRIBIDI_ENTRY is defined during configure, then it is defined again
during compile in fribidi-common.h.
Signed-off-by: Changqing Li <changqing.li@windriver.com>
=> fribidi-common.h: define FRIBIDI_ENTRY when it is not defined

gen.tab/gen-joining-type-tab.c
fix #160
https://github.com/fribidi/fribidi/blob/a2dd9351a0f21153ccdeb291c9679024c453699f/gen.tab/unidata/ArabicShaping.txt#L92-L100
https://www.unicode.org/Public/UNIDATA/extracted/DerivedJoiningType.txt
=> fix typo in transparent_general_categories[]

.ci/build-c2man.sh, .github/workflows/make.yml
Should we remove `.travis.yml`, `appveyor.yml`?
----
**Why not add `macos-latest` into `matrix.os`?**
`macos-latest` == `macos-10.15`, with Clang/LLVM 12.0.0, it compiles with newer c standard  by default. And then we have errors.
> By default, Clang builds C code in GNU C17 mode
> 
> [Language Compatibility](https://clang.llvm.org/compatibility.html#inline)
Maybe we need to set some old `-std` version, or use old clang, or update c2man code, or replace c2man with something new.
Several attempts: https://github.com/Aeg-dev/c2man/commits/test-ci
=> Open GitHub CI: build with make

lib/meson.build
It is needed when fribidi is used as subproject and is static linked on
Windows. The pkg-config file already contains it for the same reason.
=> Add -DFRIBIDI_LIB_STATIC to libfribidi_dep

.github/workflows/make.yml, .github/workflows/meson.yml, lib/meson.build, meson.build
With this change, fribidi can be consumed as a subproject without making any changes to the build files of a project. All you need to do is provide a wrap file with a `[provide]` section:
https://mesonbuild.com/Wrap-dependency-system-manual.html#provide-section
This is also necessary because otherwise projects need to hard-code the subproject name, which might be `fribidi` when using `wrap-git` or `fribidi-1.0.12` when using `wrap-file` (to build from a release tarball). This can cause conflicts between different subprojects that consume fribidi differently.
Other projects like glib, cairo, pango, etc already do this.
Bumped the minimum version of Meson to 0.54 because that's the release that added this feature. It was released almost three years ago, so should be fine.
=> meson: Override dependencies to improve usage as a subproject

doc/meson.build
doc/meson.build:2: WARNING: Project targets '>= 0.54' but uses feature deprecated since '0.48.0': module python3.
WARNING: You should add the boolean check kwarg to the run_command call.
=> meson: fix two meson warnings

bin/meson.build, meson.build
The fribidi binary is needed by the unit test setup, so if tests are enabled we need to build it even if binaries are disabled. We just won't install it in that case.
Fixes #198
=> meson: fix build with -Dbin=false and -Dtests=true

lib/debug.h
Clang does not accept that, and errors out like so:
../../../../pexip/external/fribidi/lib/fribidi.c:84:3: error: expected expression
DBG ("in fribidi_remove_bidi_marks");
^
../../../../pexip/external/fribidi/lib/debug.h:84:32: note: expanded from macro 'DBG'
if (fribidi_debug_status()) { MSG(FRIBIDI ": " s "\n"); } \
^
../../../../pexip/external/fribidi/lib/debug.h:57:2: note: expanded from macro 'MSG'
FRIBIDI_FPRINTF(FRIBIDI_STDERR_ s); \
^
../../../../pexip/external/fribidi/lib/debug.h:50:26: note: expanded from macro 'FRIBIDI_FPRINTF' # define FRIBIDI_FPRINTF fprintf
^
/usr/include/x86_64-linux-gnu/bits/stdio2.h:113:62: note: expanded from macro 'fprintf'
__fprintf_chk (stream, __USE_FORTIFY_LEVEL - 1, __VA_ARGS__)
=> debug: don't pass a comma "," in a #define
